# Generated by Django 4.2.23 on 2025-12-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_url_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('email', 'Email'), ('phone', 'Teléfono'), ('website', 'Sitio Web')], max_length=20, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('display_text', models.CharField(blank=True, max_length=100)),
                ('icon_class', models.CharField(default='bi bi-link', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Enlace de Contacto',
                'verbose_name_plural': 'Enlaces de Contacto',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
